---
title: "TidyTuesday2"
format: html
editor: visual
author: "Matté Lopez"
---

## Research Question:

### How does plumbing access in large counties across the U.S. compare?

```{r}
library(tidytuesdayR)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(tidyr)
library(stringr)
library(grid)
library(gridExtra) 
```

```{r}
water_insecurity_2022 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-01-28/water_insecurity_2022.csv')
water_insecurity_2023 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-01-28/water_insecurity_2023.csv')


selectcounties <- c("St.Louis County, Missouri", "Los Angeles County, California", "Dallas County, Texas", "Broward County, Texas","Fairfax County, Virginia","Honolulu County, Hawaii", "Philadelphia County, Pennsylvania", "New York County, New York")

countydata <- water_insecurity_2022 %>%
  filter(name %in% selectcounties)

countydata2 <- water_insecurity_2023 %>%
  filter(name %in% selectcounties)


Plot1<-ggplot(countydata) + geom_col(aes(x=name,y=percent_lacking_plumbing),fill="darkred")+
  scale_y_continuous(limits = c(0, 0.12))+theme_linedraw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),axis.title.x=element_text())+labs(y="Percent Lacking Plumbing",x=NULL)

Plot2<-ggplot(countydata2)+geom_col(aes(x=name,y=percent_lacking_plumbing),fill="darkred")+
  scale_y_continuous(limits = c(0, 0.12))+theme_linedraw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),axis.title.x=element_text())+labs(y="Percent Lacking Plumbing",x=NULL)

grid.arrange(Plot1, Plot2, ncol = 2,top = textGrob ("Plumbing Access in U.S. counties 2022 vs 2023 ", gp = gpar(fontsize = 14, fontface = "plain")))
```
